main/urls.py
from django.urls import path

from main.views import MainPageView

urlpatterns = [
    path('', MainPageView.as_view(), name='main'),
    path('main/', MainPageView.as_view(), name='main'),
]

mftrade/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('account/', include('account.urls')),
    path('references/', include('references.urls', namespace="references")),
    path('documents/', include('documents.urls', namespace="documents")),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

references/urls.py
from django.urls import path

from references.article import views as article_views
from references.contragent import views as contragent_views
from references.measure import views as measure_views
from references.stock import views as stock_views
from references.views import ReferencesView

app_name = 'references'

urlpatterns = [
    path('', ReferencesView.as_view(), name='main'),
    path('article/', article_views.article_list, name='article_list'),
    path('article/<int:group_id>/', article_views.article_list,
         name='article_list_by_group'),
    path('article/<int:group_id>/edit/', article_views.article_group_edit,
         name='article_group_edit'),
    path('article/new/', article_views.article_group_edit,
         name='article_group_new'),
    path('article/element/<int:article_id>/', article_views.article_detail,
         name='article_detail'),
    path('article/element/new/', article_views.article_detail,
         name='article_new'),
    path('contragent/', contragent_views.ContragentListView.as_view(),
         name='contragent_list'),
    path('contragent/new/', contragent_views.ContragentCreateView.as_view(),
         name='contragent_new'),
    path('contragent/<int:pk>/edit',
         contragent_views.ContragentUpdateView.as_view(),
         name='contragent_detail'),
    path('contragent/<int:pk>/delete',
         contragent_views.ContragentDeleteView.as_view(),
         name='contragent_delete'),
    path('measure/', measure_views.MeasureListView.as_view(),
         name='measure_list'),
    path('measure/new/', measure_views.MeasureCreateView.as_view(),
         name='measure_new'),
    path('measure/<int:pk>/edit',
         measure_views.MeasureUpdateView.as_view(),
         name='measure_detail'),
    path('measure/<int:pk>/',
         measure_views.MeasureUpdateView.as_view(),
         name='measure_detail'),
    path('measure/<int:pk>/delete',
         measure_views.MeasureDeleteView.as_view(),
         name='measure_delete'),
    path('stock/', stock_views.StockListView.as_view(),
         name='stock_list'),
    path('stock/new/', stock_views.StockCreateView.as_view(),
         name='stock_new'),
    path('stock/<int:pk>/edit', stock_views.StockUpdateView.as_view(),
         name='stock_detail'),
    path('stock/<int:pk>/delete', stock_views.StockDeleteView.as_view(),
         name='stock_delete'),
]

references/article/models.py
from django.db import models
from django.urls import reverse

from ..contragent.models import Contragent
from ..measure.models import Measure


# Create your models here.


# Справочник группа товаров
class ArticleGroup(models.Model):
    title = models.CharField(max_length=32, unique=True, db_index=True,
                             verbose_name='Наименование')
    parent = models.ForeignKey('self', blank=True, null=True,
                               on_delete=models.SET_NULL,
                               verbose_name='Группа')
    description = models.TextField(blank=True, null=True,
                                   verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа товара'
        verbose_name_plural = 'Группы товара'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('references:article_list_by_group', args=[self.id])


# Справочник товаров
class Article(models.Model):
    title = models.CharField(max_length=128, unique=True, db_index=True,
                             verbose_name='Наименование')
    article = models.CharField(max_length=32, db_index=True,
                               verbose_name='Артикул')
    category = models.ForeignKey(ArticleGroup, on_delete=models.PROTECT,
                                 db_index=True, verbose_name='Группа')
    image = models.ImageField(blank=True, upload_to='images/goods/',
                              verbose_name='Изображение')
    description = models.TextField(blank=True, verbose_name='Описание')
    supplier = models.ForeignKey(Contragent, on_delete=models.PROTECT,
                                 blank=True, null=True,
                                 verbose_name='Производитель')
    unit_m = models.ForeignKey(Measure, on_delete=models.PROTECT,
                               null=True, verbose_name='Ед.изм.')
    size_w = models.PositiveIntegerField(blank=True, null=True,
                                         verbose_name='Длина')
    size_h = models.PositiveIntegerField(blank=True, null=True,
                                         verbose_name='Высота')
    size_d = models.PositiveIntegerField(blank=True, null=True,
                                         verbose_name='Ширина')
    weight = models.PositiveIntegerField(blank=True, null=True,
                                         verbose_name='Масса')

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('references:article_detail', args=[self.id])

references/category/models.py
from django.db import models


# Create your models here.


# Справочник Группы
class Category(models.Model):
    title = models.CharField(max_length=32, unique=True, db_index=True,
                             verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title

references/contragent/models.py
from django.db import models
from django.urls import reverse


# Контрагент


class Contragent(models.Model):
    title = models.CharField(max_length=64, db_index=True,
                             verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Контрагент'
        verbose_name_plural = 'Контрагенты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('references:contragent_detail',
                       kwargs={'pk': self.pk})

references/measure/models.py
from django.db import models
from django.urls import reverse


# Справочник Единицы измерения


class Measure(models.Model):
    title = models.CharField(max_length=8, unique=True, db_index=True,
                             verbose_name='Наименование')
    description = models.CharField(max_length=64, verbose_name='Описание')

    class Meta:
        verbose_name = 'Единица измерения'
        verbose_name_plural = 'Единицы измерения'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('references:measure_detail',
                       kwargs={'pk': self.pk})

references/models.py
# Create your models here.

references/stock/models.py
from django.db import models
from django.urls import reverse


# Справочник складов
class Stock(models.Model):
    title = models.CharField(max_length=32, unique=True, db_index=True,
                             verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Склад'
        verbose_name_plural = 'Склады'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('references:stock_detail',
                       kwargs={'pk': self.pk})

references/article/forms.py
from django import forms

from .models import ArticleGroup, Article


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = ArticleGroup
        fields = ['title', 'parent', 'description']


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        #        fields = ['title', 'article', 'category', 'image', 'description',
        #                 'supplier', 'unit_m', 'size_w', 'size_h', 'size_d', 'weight']
        # Можно использовать
        fields = '__all__'

references/article/views.py
from django.db.models import ProtectedError
from django.shortcuts import render, get_object_or_404

from references.article.models import ArticleGroup, Article
from .forms import GroupCreateForm, ArticleCreateForm


def article_list(request, group_id=None):
    group = None
    groups = ArticleGroup.objects.all()
    articles = Article.objects.all()
    if group_id:
        group = get_object_or_404(ArticleGroup, pk=group_id)
        groups = groups.filter(parent=group)
        articles = articles.filter(category=group)
    return render(request, 'references/article/list.html',
                  {'group': group, 'groups': groups, 'articles': articles})


def article_group_edit(request, group_id=None):
    if group_id is not None:
        group = get_object_or_404(ArticleGroup, pk=group_id)
    else:
        group = ArticleGroup()
    error = 0
    if request.method == 'POST':
        form = GroupCreateForm(request.POST, instance=group)
        if "Edit" in request.POST:
            if form.is_valid():
                cd = form.cleaned_data
                group.title = cd['title']
                group.parent = cd['parent']
                group.description = cd['description']
                group.save()
        elif "Delete" in request.POST:
            try:
                group.delete()  # удаление категории
            except ProtectedError:
                # тут нужно нормально переписать обработку ошибок
                error = 1
                return render(request, 'references/article/group.html',
                              {'group': group, 'form': form, 'error': error})
            return render(request, 'references/article/list.html')
        return render(request, 'references/article/list.html',
                      {'group': group})
    else:
        form = GroupCreateForm(instance=group)
    return render(request, 'references/article/group.html',
                  {'group': group, 'form': form, 'error': error})


def article_detail(request, article_id=None):
    if article_id is not None:
        article = get_object_or_404(Article, pk=article_id)
    else:
        article = Article()
    error = 0
    if request.method == 'POST':
        form = ArticleCreateForm(request.POST, request.FILES, instance=article)
        if "Edit" in request.POST:
            if form.is_valid():
                form.save()
        elif "Delete" in request.POST:
            try:
                article.delete()  # удаление категории
            except ProtectedError:
                # тут нужно нормально переписать обработку ошибок
                error = 1
                return render(request, 'references/article/detail.html',
                              {'article': article,
                               'form': form,
                               'error': error})
        return render(request, 'references/article/list.html',
                      {'group': article.category})
    else:
        form = ArticleCreateForm(instance=article)
    return render(request, 'references/article/detail.html',
                  {'article': article, 'form': form, 'error': error})

references/category/views.py
# Create your views here.

references/contragent/views.py
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Contragent


class ContragentListView(ListView):
    model = Contragent
    template_name = 'references/contragent/list.html'


class ContragentCreateView(CreateView):
    model = Contragent
    fields = '__all__'
    #    form_class = ContragentCreateForm
    template_name = 'references/contragent/detail.html'
    success_url = reverse_lazy('references:contragent_list')


class ContragentUpdateView(UpdateView):
    model = Contragent
    fields = '__all__'
    template_name = 'references/contragent/detail.html'
    success_url = reverse_lazy('references:contragent_list')


class ContragentDeleteView(DeleteView):
    model = Contragent
    template_name = 'references/contragent/confirm.html'
    success_url = reverse_lazy('references:contragent_list')

    def post(self, request, *args, **kwargs):
        if self.request.POST.get("confirm_delete"):
            queryset = self.get_object()
            try:
                queryset.delete()
            except ProtectedError:
                error = 1
                return render(request, 'references/contragent/confirm.html',
                              {'error': error})
            return HttpResponseRedirect(self.success_url)
        elif self.request.POST.get("cancel"):
            return HttpResponseRedirect(self.success_url)
        else:
            return HttpResponseRedirect(self.success_url)

references/measure/views.py
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Measure


class MeasureListView(ListView):
    model = Measure
    template_name = 'references/measure/list.html'


class MeasureCreateView(CreateView):
    model = Measure
    fields = '__all__'
    template_name = 'references/measure/detail.html'
    success_url = reverse_lazy('references:measure_list')


class MeasureUpdateView(UpdateView):
    model = Measure
    fields = '__all__'
    template_name = 'references/measure/detail.html'
    success_url = reverse_lazy('references:measure_list')


class MeasureDeleteView(DeleteView):
    model = Measure
    template_name = 'references/measure/confirm.html'
    success_url = reverse_lazy('references:measure_list')

    def post(self, request, *args, **kwargs):
        if self.request.POST.get("confirm_delete"):
            queryset = self.get_object()
            try:
                queryset.delete()
            except ProtectedError:
                error = 1
                return render(request, 'references/measure/confirm.html',
                              {'error': error})
            return HttpResponseRedirect(self.success_url)
        elif self.request.POST.get("cancel"):
            return HttpResponseRedirect(self.success_url)
        else:
            return HttpResponseRedirect(self.success_url)

references/stock/views.py
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Stock


class StockListView(ListView):
    model = Stock
    template_name = 'references/stock/list.html'


class StockCreateView(CreateView):
    model = Stock
    fields = '__all__'
    template_name = 'references/stock/detail.html'
    success_url = reverse_lazy('references:stock_list')


class StockUpdateView(UpdateView):
    model = Stock
    fields = '__all__'
    template_name = 'references/stock/detail.html'
    success_url = reverse_lazy('references:stock_list')


class StockDeleteView(DeleteView):
    model = Stock
    template_name = 'references/stock/confirm.html'
    success_url = reverse_lazy('references:stock_list')

    def post(self, request, *args, **kwargs):
        if self.request.POST.get("confirm_delete"):
            queryset = self.get_object()
            try:
                queryset.delete()
            except ProtectedError:
                error = 1
                return render(request, 'references/stock/confirm.html',
                              {'error': error})
        return HttpResponseRedirect(self.success_url)

references/views.py
from django.views.generic.base import TemplateView

from generic.mixins import CategoryListMixin


# Create your views here.


class ReferencesView(TemplateView, CategoryListMixin):
    template_name = 'references/references.html'

templates/references/article/delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Удаление группы</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Уверенны, что хотите удалить "{{ post.title }}"?</p>
        <p>(Если в группе есть элементы, группу удалить не удастся.)</p>
        <input type="submit" value="Да"/>
    </form>
{% endblock content %}

templates/references/article/detail.html
{% extends "group_list.html" %}
{% block title %}
    {% if article %}{{ article.title }}{% else %} Новый товар {% endif %}
{% endblock %}
{% block subheader %}
    <h2 class="refname">Товары и услуги</h2>
    <button name="Edit" form="form_article_edit"> Записать</button>
    <button name="Close" form="form_article_edit"> Закрыть</button>
    <p class="separator"></p>
    <button name="Delete" form="form_article_edit"> Удалить</button>
{% endblock %}
{% block detail %}
    <div class="product-detail">
        {% if error == 1 %}
            <h2> Сначала удалите все записи, ссылающиеся на этот товар</h2>
            <form action="{{ article.get_absolute_url }}">
                <button> Закрыть</button>
            </form>
        {% else %}
            <form id="form_article_edit" action="." method="post"
                  enctype="multipart/form-data">
                <table>
                    {{ form.as_table }}
                    {% csrf_token %}
                </table>
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/references/article/group.html
{% extends "group_list.html" %}
{% block title %}
    {% if group %}{{ group.title }}{% else %} Новая группа {% endif %}
{% endblock %}
{% block subheader %}
    <h2 class="refname">Группы товаров</h2>
    <button name="Edit" form="form_group_edit"> Записать</button>
    <button name="Close" form="form_group_edit"> Закрыть</button>
    <p class="separator"></p>
    <button name="Delete" form="form_group_edit"> Удалить</button>
{% endblock %}
{% block detail %}
    {% if error == 1 %}
        <h2> Сначала удалите или перенесите товары из этой категории!</h2>
        <form action="{{ group.get_absolute_url }}">
            <button> Закрыть</button>
        </form>
    {% else %}
        <form id="form_group_edit" action="." method="post">
            <table>
                {{ form.as_table }}
                {% csrf_token %}
            </table>
        </form>
    {% endif %}
{% endblock %}

templates/references/article/list.html
{% extends "group_list.html" %}
{% load static %}
{% block title %}
    {% if group %}{{ group.title }}{% else %} Товары {% endif %}
{% endblock %}

{% block subheader %}
    <h2 class="refname">Справочник Товары</h2>
    <form action="{% url "references:article_group_new" %}">
        <button> +Группа</button>
    </form>
    <form action="{% url "references:article_new" %}">
        <button> +Товар</button>
    </form>
    <p class="separator"></p>
    <form action="{% url "references:main" %}">
        <button> Закрыть</button>
    </form>

{% endblock %}

{% block menu %}
    <h3>Группы</h3>
    <ul>
        <li class="selected">
            <a href="{% url "references:article_list" %}">
                {% if group %}{{ group.title }}{% else %} Все {% endif %}</a>
            <ul>
                {% for g in groups %}
                    {% if g.parent == group %}
                        <li>
                            <a href="{{ g.get_absolute_url }}">{{ g.title }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </li>
    </ul>
{% endblock %}
{% block detail %}
    {% if group %}
        <h1>{{ group.title }}</h1>
        <p>{{ group.description }}</p>
    {% else %}
        <h1> Товары </h1>
    {% endif %}
    {% for a in articles %}
        <div class="item">
            <a href="{{ a.get_absolute_url }}">
                <img class="img-preview" src="{% if a.image %}{{ a.image.url }}
            {% else %}{% static 'img/no-image.png' %}{% endif %}"
                     width="50"
                     alt="[x]">
            </a>
            <a href="{{ a.get_absolute_url }}">{{ a.title }}</a>
        </div>
    {% endfor %}
{% endblock %}