documents/urls.py
from django.urls import path

from documents.views import DocumentsView
from documents.invoice import views as invoice_views

app_name = 'documents'

urlpatterns = [
    path('', DocumentsView.as_view(), name='main'),
    path('inventory/', invoice_views.InvoiceListView.as_view(),
         name='inventory'),
    path('inventory/new/', invoice_views.InvoiceCreateView.as_view(),
         name='inventory_new'),
    path('inventory/<int:pk>/delete',invoice_views.InvoiceDeleteView.as_view(),
         name='inventory_delete')
]

main/urls.py
from django.urls import path

from main.views import MainPageView

urlpatterns = [
    path('', MainPageView.as_view(), name='main'),
    path('main/', MainPageView.as_view(), name='main'),
]

mftrade/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('account/', include('account.urls')),
    path('references/', include('references.urls', namespace="references")),
    path('documents/', include('documents.urls', namespace="documents")),
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

references/urls.py
from django.urls import path

from references.article import views as article_views
from references.contragent import views as contragent_views
from references.measure import views as measure_views
from references.stock import views as stock_views
from references.views import ReferencesView

app_name = 'references'

urlpatterns = [
    path('', ReferencesView.as_view(), name='main'),
    path('article/', article_views.article_list, name='article_list'),
    path('article/<int:group_id>/', article_views.article_list,
         name='article_list_by_group'),
    path('article/<int:group_id>/edit/', article_views.article_group_edit,
         name='article_group_edit'),
    path('article/new/', article_views.article_group_edit,
         name='article_group_new'),
    path('article/element/<int:article_id>/', article_views.article_detail,
         name='article_detail'),
    path('article/element/new/', article_views.article_detail,
         name='article_new'),
    path('contragent/', contragent_views.ContragentListView.as_view(),
         name='contragent_list'),
    path('contragent/new/', contragent_views.ContragentCreateView.as_view(),
         name='contragent_new'),
    path('contragent/<int:pk>/edit',
         contragent_views.ContragentUpdateView.as_view(),
         name='contragent_detail'),
    path('contragent/<int:pk>/delete',
         contragent_views.ContragentDeleteView.as_view(),
         name='contragent_delete'),
    path('measure/', measure_views.MeasureListView.as_view(),
         name='measure_list'),
    path('measure/new/', measure_views.MeasureCreateView.as_view(),
         name='measure_new'),
    path('measure/<int:pk>/edit',
         measure_views.MeasureUpdateView.as_view(),
         name='measure_detail'),
    path('measure/<int:pk>/',
         measure_views.MeasureUpdateView.as_view(),
         name='measure_detail'),
    path('measure/<int:pk>/delete',
         measure_views.MeasureDeleteView.as_view(),
         name='measure_delete'),
    path('stock/', stock_views.StockListView.as_view(),
         name='stock_list'),
    path('stock/new/', stock_views.StockCreateView.as_view(),
         name='stock_new'),
    path('stock/<int:pk>/edit', stock_views.StockUpdateView.as_view(),
         name='stock_detail'),
    path('stock/<int:pk>/delete', stock_views.StockDeleteView.as_view(),
         name='stock_delete'),
]

documents/invoice/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from references.article.models import Article
from references.contragent.models import Contragent
from references.measure.models import Measure
from references.stock.models import Stock


# Create your models here.


# документ Накладная
class Invoice(models.Model):
    STATUS_CHOICES = (
        ('buy', 'Покупка'),
        ('sell', 'Продажа'),
        ('off', 'Списание'),
        ('return', 'Возврат'),
        ('inventory', 'Инвентаризация'),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.PROTECT,
                                verbose_name='Автор')
    number = models.CharField(max_length=32, verbose_name='Номер')
    invoice_date = models.DateTimeField(verbose_name='Дата')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              db_index=True, verbose_name='Вид операции')
    supplier = models.ForeignKey(Contragent, null=True,
                                 on_delete=models.SET_NULL,
                                 verbose_name='Поставщик')
    stock = models.ForeignKey(Stock, on_delete=models.PROTECT,
                              verbose_name='Склад')
    summa = models.DecimalField(max_digits=19, decimal_places=2,
                                verbose_name='Сумма')

    class Meta:
        ordering = ('invoice_date', 'status', 'supplier',)
        verbose_name = 'Накладная'
        verbose_name_plural = 'Накладные'

    def __str__(self):
        return 'Накладная № {} от {}'.format(self.number, self.invoice_date)

    def get_absolute_url(self):
        return reverse('documents:inventory_detail',
                       kwargs={'pk': self.pk})


class InvoiceTable(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE,
                                verbose_name='Документ')
    product = models.ForeignKey(Article, on_delete=models.PROTECT,
                                verbose_name='Номенклатура')
    quantity = models.DecimalField(max_digits=19, decimal_places=3, default=0,
                                   verbose_name='Количество')
    mesure = models.ForeignKey(Measure, on_delete=models.PROTECT,
                               verbose_name='Ед.изм.')
    price = models.DecimalField(max_digits=19, decimal_places=2, default=0.00,
                                verbose_name='Цена')
    discont = models.DecimalField(max_digits=19, decimal_places=2,
                                  default=0.00, verbose_name='Скидка')
    summa = models.DecimalField(max_digits=19, decimal_places=2,
                                default=0.00, verbose_name='Сумма')

documents/models.py
# Create your models here.

documents/invoice/forms.py
from django.forms import ModelForm, inlineformset_factory
from .models import Invoice, InvoiceTable


class InvoiceEditForm(ModelForm):
    class Meta:
        model = Invoice
        exclude = ('user', 'status', 'summa')


InvoiceEditFormSet = inlineformset_factory(Invoice, InvoiceTable,
                                           form=InvoiceEditForm,
                                           can_delete=True,
                                           can_order=True,
                                           extra=1,
                                           )
items_formset = InvoiceEditFormSet
item_forms = items_formset()

documents/invoice/views.py
from django.db import transaction
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .models import Invoice
from .forms import InvoiceEditForm, InvoiceEditFormSet


class InvoiceListView(ListView):
    model = Invoice
    queryset = Invoice.objects.filter(status='inventory')
    template_name = 'documents/invoice/list.html'


class InvoiceCreateView(CreateView):
    model = Invoice
    form_class = InvoiceEditForm
#    fields = ['number', 'invoice_date', 'supplier', 'stock']
    template_name = 'documents/invoice/detail.html'
    success_url = reverse_lazy('documents:inventory')

    def get_context_data(self, **kwargs):
        data = super(InvoiceCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['invoicetable'] = InvoiceEditFormSet(self.request.POST)
        else:
            data['invoicetable'] = InvoiceEditFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        invoicetable = context['invoicetable']
        with transaction.atomic():
            form.instance.user = self.request.user
            form.instance.status = Invoice.STATUS_CHOICES.inventory
            self.object = form.save()
            if invoicetable.is_valid():
                invoicetable.instance = self.object
                invoicetable.save()
        return super(InvoiceCreateView, self).form_valid(form)


class InvoiceDeleteView(DeleteView):
    model = Invoice
    template_name = 'documents/invoice/confirm.html'
    success_url = reverse_lazy('documents:inventory')

documents/views.py
from django.views.generic.base import TemplateView

from generic.mixins import CategoryListMixin


class DocumentsView(TemplateView, CategoryListMixin):
    template_name = 'documents/documents.html'

templates/documents/invoice/confirm.html
{% extends "reference.html" %}
{% block title %}
    Удаление элемента
{% endblock %}
{% block subheader %}
    <h2 class="refname">Склады</h2>
{% endblock %}
{% block detail %}
    {% if error == 1 %}
        <h2> Сначала удалите все записи, ссылающиеся на этот элемент</h2>
        <form action="{% url 'references:stock_list' %}">
            <button> Закрыть</button>
        </form>
    {% else %}
        <h2> Вы действительно хотите удалить запись?</h2>
        <p>{{ object }}</p>
        <form action="" method="post">
            {% csrf_token %}
            <button name="confirm_delete" value="Confirm deletion"> Удалить
            </button>
            <button name="cancel" value="Cancel"> Отмена!</button>
        </form>
    {% endif %}
{% endblock %}

templates/documents/invoice/detail.html
{% extends "simple_list.html" %}
{% load static %}
{% block title %}
    {% if object %}{{ object.title }}{% else %} Новый документ {% endif %}
{% endblock %}
{% block additional_css %}
        <script type="text/javascript" src={% static "js/scripts.js" %}></script>
{% endblock %}
{% block subheader %}
    <h2 class="refname">Инвентаризация</h2>
    <button name="Edit" form="form_edit"> Записать</button>
    <form action="{% url "documents:inventory" %}">
        <button name="Close"> Закрыть!</button>
    </form>
    <p class="separator"></p>
    {% if object %}
        <form action="{% url 'documents:inventory_delete' pk=object.pk %}">
            <button name="Delete"> Удалить</button>
        </form>
    {% endif %}

{% endblock %}
{% block detail %}
    <h2>Заголовок</h2>
    {{ invoicetable.management_form }}
    <script type="text/html" id="item-template">
        <div id="item-__prefix__">
            {{ invoicetable.empty_form.as_table }}
        </div>
    </script>
    <form action="" method="post">
        <table>
        {{ form.as_table }}
        {% csrf_token %}
        </table>
        <div id="items-form-container">
            {% for item_form in invoicetable.forms %}
                <div id="item-{{ forloop.counter0 }}">
                    {{ item_form.id }}
                    {{ item_form.errors.as_ul }}
                    {{ item_form.as_table }}
                </div>
            {% endfor %}
        </div>
    </form>
    <button id="add-item-button" class="btn btn-info add-item">Добавить</button>
{% endblock %}

templates/documents/invoice/list.html
{% extends "simple_list.html" %}
{% block title %}
    Инвентаризация
{% endblock %}

{% block subheader %}
    <h2 class="refname">Документы Инвентаризация</h2>
    <form action="{% url "documents:inventory_new" %}">
        <button> +Документ</button>
    </form>
    <p class="separator"></p>
    <form action="{% url "documents:main" %}">
        <button> Закрыть</button>
    </form>
{% endblock %}

{% block detail %}
    {% for doc in object_list %}
        <div class="item">
            <a href="{{ doc.get_absolute_url }}">{{ doc }}</a>
        </div>
    {% empty %}
        <div class="item">
            <p>Документы отсутствуют</p>
        </div>
    {% endfor %}
{% endblock %}